#!/bin/bash
# pollen-manager/build.sh — workaround build script.
#
# The upstream `amc package add` + mosaic-build.sh only compile
# each package's facade.am into the archive, missing the classes
# defined in `sources = [...]` siblings (WebApp/Static/Session
# for amalgame-web, etc.). This script rebuilds the multi-source
# archives into ./build/ locally and re-links against them.
#
# It also (re)generates amalgame.lock from the package cache before
# compiling: since amc v0.8.51 the resolver only attaches a package
# whose EXACT locked version (tag_rev) is present in the cache, and
# silently skips it otherwise — a stale lock pinning a pruned version
# turns into a confusing `Unknown symbol`. Regenerating the lock from
# whatever is actually cached keeps the build reproducible.
#
# Delete me once amc package add handles multi-source packages.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

PKG_BASE="$HOME/.amalgame/packages/github.com/amalgame-lang"
AMC_RT="$HOME/.local/share/amalgame/runtime"
AMC_LIB="$HOME/.local/share/amalgame/lib/libamalgame.a"

mkdir -p build

# Gather -I dirs for every cached package (their headers cross-#include).
PKG_INCS=()
for d in "$PKG_BASE"/*/; do
    latest=$(ls -1 "$d" 2>/dev/null | sort -V | tail -1)
    [ -d "$d$latest/runtime" ] && PKG_INCS+=(-I"$d$latest/runtime")
done

# Short, human-friendly lock name for a cached repo dir. amc matches a
# package by the `namespace` in its toml, not by this name, so it is
# free-form — but keep the historical short names readable.
lock_name_for() {
    case "$1" in
        amalgame-net-http)             echo http  ;;
        amalgame-database-nosql-redis) echo redis ;;
        amalgame-*)                    echo "${1#amalgame-}" ;;
        *)                             echo "$1" ;;
    esac
}

# Emit a universal amalgame.lock to stdout: every present cached package,
# pinned to its latest cached version dir (tag_rev). amc only *attaches*
# the packages whose namespace is actually imported (BFS over imports),
# so listing every cached package is harmless — extra entries just make a
# symbol resolvable if referenced. This is what lets a standalone
# `amc --lib` over a package's own sources resolve its cross-package deps
# (Threading / Redis are C-only — no facade.am to pass as a source, so the
# lock-driven auto-attach is the only path that registers their symbols).
gen_lock() {
    echo "# amalgame.lock — auto-generated by build.sh from the package cache"
    local d repo latest verdir
    for d in "$PKG_BASE"/*/; do
        repo=$(basename "$d")
        # Trailing `|| true`: an empty/stub package dir (no version subdir)
        # makes the glob — and then `grep -v` on empty input — return non-zero,
        # which under `set -e -o pipefail` would otherwise abort the build.
        latest=$(ls -d "$d"*/ 2>/dev/null | grep -v '_clone/$' | sort -V | tail -1 || true)
        [ -n "$latest" ] || continue
        [ -f "${latest}amalgame.toml" ] || continue
        verdir=$(basename "$latest")
        printf '\n[[package]]\nname = "%s"\ngit  = "github.com/amalgame-lang/%s"\ntag  = "%s"\nrev  = "%s"\n' \
            "$(lock_name_for "$repo")" "$repo" "${verdir%_*}" "${verdir##*_}"
    done
}

# Rebuild a package's archive locally with ALL its sources (the upstream
# archive only contains facade.am). The source list is read from the
# package's own manifest ([stdlib].facade + [stdlib].sources) so it never
# goes stale when the package gains a file (template.am, powered_by.am …).
rebuild_pkg() {
    local pkg_name=$1 cls=$2
    local pkg_dir
    pkg_dir=$(ls -d "$PKG_BASE/amalgame-${pkg_name}/"*/ | grep -v '_clone/$' | sort -V | tail -1)
    pkg_dir=${pkg_dir%/}
    local stem="build/${cls}-multi"

    local facade srcs
    facade=$(grep -E '^[[:space:]]*facade' "$pkg_dir/amalgame.toml" | grep -oE '"[^"]+"' | tr -d '"' || true)
    srcs=$(sed -n '/sources/,/\]/p' "$pkg_dir/amalgame.toml" | grep -oE '"[A-Za-z0-9_]+\.am"' | tr -d '"' || true)

    echo "→ rebuilding amalgame-${pkg_name} archive (${cls}) from $(basename "$pkg_dir")"
    # amc needs a lockfile in CWD to resolve this package's own deps.
    gen_lock > "$pkg_dir/amalgame.lock"
    (
        trap 'rm -f "$pkg_dir/amalgame.lock"' EXIT
        cd "$pkg_dir" && amc --lib --quiet $facade $srcs -o "$ROOT/$stem" >/dev/null
    )
    gcc -O2 -I"$AMC_RT" "${PKG_INCS[@]}" \
        -I"$pkg_dir/runtime" \
        -c "$stem.c" -o "$stem.o"
    ar rcs "build/libamalgame-pkg-${cls}.a" "$stem.o"
}

# amalgame-web — multi-source (sources read from its manifest).
rebuild_pkg web Router

# Pick up the upstream facade-only archives for everything else
# (single-class packages don't have the multi-source problem).
get_pkg_archive() {
    local pkg=$1 cls=$2
    # sort -V + skip *_clone scratch dirs : lexical sort would pick
    # v0.1.9 over v0.1.12 ("9" > "1"), linking a stale archive.
    local d=$(ls -d "$PKG_BASE/amalgame-${pkg}/"*/ | grep -v '_clone/$' | sort -V | tail -1)
    d=${d%/}
    echo "$d/build/linux-x86_64/libamalgame-pkg-${cls}.a"
}

# Regenerate our own lock from the cache so `amc server.am` resolves
# Web / Net.Http / Threading / DateTime against present versions.
echo "→ regenerating amalgame.lock from cache"
gen_lock > amalgame.lock

# Routes regen + amc → server.c.
echo "→ regenerating _routes.am"
/home/neitsab/Développement/mosaic/tools/mosaic-routes.sh app _routes.am
echo "→ amc server.am _routes.am → server.c"
amc --quiet server.am _routes.am -o server >/dev/null

# Link with our locally-rebuilt web archive first so it wins over
# the upstream incomplete one.
echo "→ link"
gcc -O2 -I"$AMC_RT" "${PKG_INCS[@]}" \
    -Wno-int-conversion -Wno-incompatible-pointer-types \
    server.c \
    -Wl,--start-group \
    build/libamalgame-pkg-Router.a \
    "$(get_pkg_archive crypto Sha256)" \
    "$(get_pkg_archive tls TlsConfig)" \
    "$(get_pkg_archive async Async)" \
    "$(get_pkg_archive net-http HttpRequest)" \
    "$(get_pkg_archive datetime DateTime)" \
    "$(get_pkg_archive random Random)" \
    "$(get_pkg_archive logging Log)" \
    "$(get_pkg_archive database-nosql-redis Redis)" \
    "$(get_pkg_archive threading Threading)" \
    "$(get_pkg_archive pollen Pollen)" \
    "$AMC_LIB" \
    -Wl,--end-group \
    -lgc -lm -lz -lcrypto -lssl -lnghttp2 -lpthread \
    -o server

echo "✓ Built ./server"
